# -*- coding: utf-8 -*-
"""snowflake-svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cP2tYoRGa4crlv8FetvcrrsOZSfeF_F5
"""

!pip install snowflake-connector-python

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
import snowflake.connector
conn = snowflake.connector.connect(
    user='GOKILA',
    password= 'Btsarmy0739177',
    account= 'TGULZJN-YG81730',
    database= 'water',
    schema= 'PUBLIC',
    warehouse= 'COMPUTE_WH'
)

query = "SELECT * from water_potability"
df = pd.read_sql(query,conn)
df

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.isnull().sum()

from scipy.stats import zscore
z_scores = zscore(df)
df[np.abs(z_scores)>2.5]

log_transform = np.log1p(df)

print(log_transform.head())

from scipy.stats.mstats import winsorize
numeric_cols=df.select_dtypes(include= np.number).columns
for col in numeric_cols:
  df[col]=winsorize(df[col], limits=[0,0.1])
print(df)

import seaborn as sns
sns.boxplot(df)

"""## Data Preprocessing: Handle Missing Values

Before training the SVM model, it's crucial to handle missing values. I will impute the missing values in 'PH', 'SULFATE', and 'TRIHALOMETHANES' columns with their respective means.
"""

for col in ['PH', 'SULFATE', 'TRIHALOMETHANES']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

print("Missing values after imputation:")
print(df.isnull().sum())

# Support Vector Machine (SVM) Implementation
# 1. Defining features (X) and target (y).
# 2. Splitting the data into training and testing sets.
# 3. Training an SVM classifier.
# 4. Making predictions and evaluating the model.

from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

X = df.drop('POTABILITY', axis=1) # Define features (X) and target (y)
y = df['POTABILITY']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = SVC(kernel='linear', random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("SVM Model Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", metrics.classification_report(y_test, y_pred))

X_2d = df[['PH', 'HARDNESS']]
y_2d = df['POTABILITY']

scaler_2d = StandardScaler()
X_2d_scaled = scaler_2d.fit_transform(X_2d)

X_train_2d, X_test_2d, y_train_2d, y_test_2d = train_test_split(X_2d_scaled, y_2d, test_size=0.3, random_state=42)

svm_model_2d = SVC(kernel='linear', random_state=42)
svm_model_2d.fit(X_train_2d, y_train_2d)

x_min, x_max = X_2d_scaled[:, 0].min() - 1, X_2d_scaled[:, 0].max() + 1
y_min, y_max = X_2d_scaled[:, 1].min() - 1, X_2d_scaled[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.02),
                     np.arange(y_min, y_max, 0.02))

Z = svm_model_2d.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

plt.figure(figsize=(10, 7))
plt.contourf(xx, yy, Z, alpha=0.8, cmap=plt.cm.coolwarm)
plt.scatter(X_2d_scaled[:, 0], X_2d_scaled[:, 1], c=y_2d, cmap=plt.cm.coolwarm, edgecolors='k')
plt.xlabel('Scaled PH')
plt.ylabel('Scaled HARDNESS')
plt.title('SVM Decision Boundary (PH vs HARDNESS)')
plt.show()